### ISSUE TITLE
components/payout

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/bitcentive#206]
- [x] wouldn't `payout.monthlyOSProjects` be the same for every `payout`?  If so, this should probably just be something on the `viewModel`. (#240: c971860f63b984a78e793b56c5a68574f512319a)

- [x] - contributionMonthsPromise should use `value`. (#239)
- [x] - `contributionMonth: ContributionMonth`(#239)
- [ ] - ~`payouts`, `getTotalForAllPayoutsForContributor` and `getOSProjectPayoutTotal` should be put in a model and tested~ superseded by #247 
- [x] - `formatDollarAmount` should be in `helpers`.

**Comment by Alfredo-Delgado** [comment]
`payout.monthlyOSProjects` are the amounts a contributor will get paid from the month's OS projects.
