### ISSUE TITLE
Perfect Sessions in CanJS / Feathers / Bitcentive

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/bitcentive#83]
## Goal

In a template

``` html
<a ($click)="loginGithub()">Github</a>
```

In the view model:

``` js
loginGithub: function(){
    feathersThing.github.loginPopup(whoWeAre);
}
```

In the view model for sessions:

``` js
Session: {value: function(){ return Session }},
session: {
  value: function(resolve){
      return Session.get({}).then(resolve);
  },
  stream: ["Session created", "Session destroyed",
                function(createdStream, destroyedStream, initialValueStream){
      return initialValueStream.merge(createdStream).merge(destroyedStream.map(null))
  }]
}
```

In the Session model:

``` js
sessionConnection = canMap( constructor( feathersSession() ) )

feathers.on("session created", function(session){
    sessionConnection.created(session)
})
feathers.on("session delete", function(session){
    sessionConnection.destroyed(session)
})
```

In the `ContributionMonth` model:

```
canMap( constructor( feathers() ) )

or

superMap([connect.replace(dataUrl, feathers)], {})
```
## Tasks
- [x] - can-event-streams
- [x] - feathers - utilities for starting authentication popup `feathersThing.github.loginPopup`
- [x] - feathers - `featherSession`
  - [x] - SSR document.cookie not populating before app init: https://github.com/donejs/done-ssr/issues/188
  - [x] - Allow feathers-authentication to check cookies after app viewModel loads: https://github.com/feathersjs/feathers-authentication/pull/317
- [ ] Fix this bug with DoneSSR cookies: https://github.com/icanjs/auth-component/issues/15
- [x] - feathers - `feathers` for socket 
  - [ ] - fallback to URL
  - [ ] - How to deal with can-zone XHR AJAX cache? - Make can-zone socket aware.
    - [ ] - steal-socket.io is working in the server when it shouldn't be: https://github.com/stealjs/steal-socket.io/issues/5
- [ ] - async values in `can-define`
- [x] - allow fixture.store like abilities with socket.io. - https://github.com/canjs/can-fixture/issues/55
- [ ] - ecosystem and documented

**Comment by justinbmeyer** [comment]
```
init: function(){
    Session.on("created", (ev, session)=>{
        this.session = session;
    })
}
```

**Comment by justinbmeyer** [comment]
```
Todo.getList({complete: true}) //-> emit( "todo find", {complete: true})
```

```
url : {
  getListData: "POST /getTodos"
}
```

```
socket: {
  getListData: "todo find",
  updateData: "todo update"
}
```

**Comment by marshallswain** [comment]
I added this additional bug to the list: https://github.com/icanjs/auth-component/issues/15
